/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asif siddique
 */
public class about extends javax.swing.JFrame {

    /**
     * Creates new form about
     */
    public about() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        abot = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        retry = new javax.swing.JButton();
        wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        abot.setFont(new java.awt.Font("Chiller", 0, 100)); // NOI18N
        abot.setForeground(new java.awt.Color(255, 255, 255));
        abot.setText("About");
        jPanel1.add(abot);
        abot.setBounds(110, 10, 180, 80);

        jLabel1.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Language : Java");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 150, 310, 30);

        jLabel2.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Platform : Netbeans IDE 8.2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 180, 310, 30);

        jLabel3.setFont(new java.awt.Font("Chiller", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Author:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 240, 310, 30);

        jLabel4.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Md. Asif Mahmod Tusher Siddique");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 270, 310, 30);

        jLabel5.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("University Of Asia Pacific");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 300, 310, 30);

        jLabel6.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Year: 2nd   Semister: !st");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 330, 310, 30);

        jLabel7.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID: 15201026");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 360, 310, 30);

        jLabel8.setFont(new java.awt.Font("Chiller", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Project Co-Ordinator:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 410, 310, 30);

        jLabel9.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ms. Anika Anwar");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 440, 310, 30);

        jLabel10.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("        @  Asif Siddique-2016");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(80, 560, 310, 30);

        jLabel11.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Project Name : Mini game- Tic Tac Toe ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 120, 310, 30);

        jLabel12.setFont(new java.awt.Font("Chiller", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Lecturer, Deprt of cse, UAp");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 470, 310, 30);

        exit.setBackground(new java.awt.Color(102, 0, 0));
        exit.setFont(new java.awt.Font("Chiller", 1, 40)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(370, 600, 53, 50);

        retry.setBackground(new java.awt.Color(0, 14, 0));
        retry.setFont(new java.awt.Font("Chiller", 1, 60)); // NOI18N
        retry.setForeground(new java.awt.Color(255, 255, 255));
        retry.setText("<");
        retry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retryActionPerformed(evt);
            }
        });
        jPanel1.add(retry);
        retry.setBounds(0, 600, 63, 50);

        wall.setIcon(new javax.swing.ImageIcon("D:\\UAP\\103\\CSE\\javatute\\Tic tac toe\\dfsd.jpg")); // NOI18N
        jPanel1.add(wall);
        wall.setBounds(0, 0, 420, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void retryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retryActionPerformed
        // TODO add your handling code here:
        tictactoe obj3=new tictactoe();
        obj3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new about().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abot;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton retry;
    private javax.swing.JLabel wall;
    // End of variables declaration//GEN-END:variables
}
